/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:ClearChargingProfileRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_CLEARCHARGINGPROFILE_H
#define OPENOCPP_OCPP20_CLEARCHARGINGPROFILE_H

#include "IMessageConverter.h"

#include "ClearChargingProfileStatusEnumType20.h"
#include "ClearChargingProfileType20.h"
#include "CustomDataType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the ClearChargingProfile messages */
static const std::string CLEARCHARGINGPROFILE_ACTION = "ClearChargingProfile";

/** @brief ClearChargingProfileReq message */
struct ClearChargingProfileReq
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief The Id of the charging profile to clear. */
    ocpp::types::Optional<int> chargingProfileId;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::ClearChargingProfileType> chargingProfileCriteria;
};

/** @brief ClearChargingProfileConf message */
struct ClearChargingProfileConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief  */
    ocpp::types::ocpp20::ClearChargingProfileStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType> statusInfo;
};

// Message converters
MESSAGE_CONVERTERS(ClearChargingProfile)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP20_CLEARCHARGINGPROFILE_H