/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:DataTransferRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_DATATRANSFER_H
#define OPENOCPP_OCPP20_DATATRANSFER_H

#include "IMessageConverter.h"

#include "CustomDataType20.h"
#include "DataTransferStatusEnumType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the DataTransfer messages */
static const std::string DATATRANSFER_ACTION = "DataTransfer";

/** @brief DataTransferReq message */
struct DataTransferReq
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief May be used to indicate a specific message or implementation. */
    ocpp::types::Optional<ocpp::types::CiStringType<50u>> messageId;
    /** @brief Data without specified length or format. This needs to be decided by both parties (Open to implementation). */
    ocpp::types::Optional<std::string> data;
    /** @brief This identifies the Vendor specific implementation */
    ocpp::types::CiStringType<255u> vendorId;
};

/** @brief DataTransferConf message */
struct DataTransferConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief  */
    ocpp::types::ocpp20::DataTransferStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType> statusInfo;
    /** @brief Data without specified length or format, in response to request. */
    ocpp::types::Optional<std::string> data;
};

// Message converters
MESSAGE_CONVERTERS(DataTransfer)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP20_DATATRANSFER_H