/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:GetInstalledCertificateIdsRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_GETINSTALLEDCERTIFICATEIDS_H
#define OPENOCPP_OCPP20_GETINSTALLEDCERTIFICATEIDS_H

#include "IMessageConverter.h"

#include "CertificateHashDataChainType20.h"
#include "CustomDataType20.h"
#include "GetCertificateIdUseEnumType20.h"
#include "GetInstalledCertificateStatusEnumType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the GetInstalledCertificateIds messages */
static const std::string GETINSTALLEDCERTIFICATEIDS_ACTION = "GetInstalledCertificateIds";

/** @brief GetInstalledCertificateIdsReq message */
struct GetInstalledCertificateIdsReq
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief Indicates the type of certificates requested. When omitted, all certificate types are requested. */
    std::vector<ocpp::types::ocpp20::GetCertificateIdUseEnumType> certificateType;
};

/** @brief GetInstalledCertificateIdsConf message */
struct GetInstalledCertificateIdsConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief  */
    ocpp::types::ocpp20::GetInstalledCertificateStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType> statusInfo;
    /** @brief  */
    std::vector<ocpp::types::ocpp20::CertificateHashDataChainType> certificateHashDataChain;
};

// Message converters
MESSAGE_CONVERTERS(GetInstalledCertificateIds)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP20_GETINSTALLEDCERTIFICATEIDS_H