/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:GetMonitoringReportRequest
                                 OCPP 2.0.1 FINAL
*/

#include "GetMonitoringReport20.h"

#include "IRpc.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Convert a GetMonitoringReport20Req from a JSON representation */
bool GetMonitoringReport20ReqConverter::fromJson(const rapidjson::Value&   json,
                                                 GetMonitoringReport20Req& data,
                                                 std::string&              error_code,
                                                 std::string&              error_message)
{
    bool ret = true;

    // customData
    if (json.HasMember("customData"))
    {
        ocpp::types::ocpp20::CustomDataType20Converter customData_converter;
        ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    // componentVariable
    if (json.HasMember("componentVariable"))
    {
        const rapidjson::Value&                               componentVariable_json = json["componentVariable"];
        ocpp::types::ocpp20::ComponentVariableType20Converter componentVariable_converter;
        for (auto it = componentVariable_json.Begin(); ret && (it != componentVariable_json.End()); ++it)
        {
            ocpp::types::ocpp20::ComponentVariableType20& item = data.componentVariable.emplace_back();
            ret = ret && componentVariable_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    // requestId
    extract(json, "requestId", data.requestId);

    // monitoringCriteria
    if (json.HasMember("monitoringCriteria"))
    {
        const rapidjson::Value& monitoringCriteria_json = json["monitoringCriteria"];
        for (auto it = monitoringCriteria_json.Begin(); ret && (it != monitoringCriteria_json.End()); ++it)
        {
            ocpp::types::ocpp20::MonitoringCriterionEnumType20& item = data.monitoringCriteria.emplace_back();
            item = ocpp::types::ocpp20::MonitoringCriterionEnumType20Helper.fromString(it->GetString());
        }
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a GetMonitoringReport20Req to a JSON representation */
bool GetMonitoringReport20ReqConverter::toJson(const GetMonitoringReport20Req& data, rapidjson::Document& json)
{
    bool ret = true;

    // customData
    if (data.customData.isSet())
    {
        ocpp::types::ocpp20::CustomDataType20Converter customData_converter;
        customData_converter.setAllocator(allocator);
        rapidjson::Document customData_doc;
        customData_doc.Parse("{}");
        ret = ret && customData_converter.toJson(data.customData, customData_doc);
        json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    // componentVariable
    if (!data.componentVariable.empty())
    {

        rapidjson::Value                                      componentVariable_json(rapidjson::kArrayType);
        ocpp::types::ocpp20::ComponentVariableType20Converter componentVariable_converter;
        componentVariable_converter.setAllocator(allocator);
        for (const ocpp::types::ocpp20::ComponentVariableType20& item : data.componentVariable)
        {
            rapidjson::Document item_doc;
            item_doc.Parse("{}");
            ret = ret && componentVariable_converter.toJson(item, item_doc);
            componentVariable_json.PushBack(item_doc.Move(), *allocator);
        }
        json.AddMember(rapidjson::StringRef("componentVariable"), componentVariable_json.Move(), *allocator);
    }

    // requestId
    fill(json, "requestId", data.requestId);

    // monitoringCriteria
    if (!data.monitoringCriteria.empty())
    {

        rapidjson::Value monitoringCriteria_json(rapidjson::kArrayType);
        for (const ocpp::types::ocpp20::MonitoringCriterionEnumType20& item : data.monitoringCriteria)
        {
            monitoringCriteria_json.PushBack(
                rapidjson::Value(ocpp::types::ocpp20::MonitoringCriterionEnumType20Helper.toString(item).c_str(), *allocator).Move(),
                *allocator);
        }
        json.AddMember(rapidjson::StringRef("monitoringCriteria"), monitoringCriteria_json.Move(), *allocator);
    }

    return ret;
}

/** @brief Convert a GetMonitoringReport20Conf from a JSON representation */
bool GetMonitoringReport20ConfConverter::fromJson(const rapidjson::Value&    json,
                                                  GetMonitoringReport20Conf& data,
                                                  std::string&               error_code,
                                                  std::string&               error_message)
{
    bool ret = true;

    // customData
    if (json.HasMember("customData"))
    {
        ocpp::types::ocpp20::CustomDataType20Converter customData_converter;
        ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    // status
    data.status = ocpp::types::ocpp20::GenericDeviceModelStatusEnumType20Helper.fromString(json["status"].GetString());

    // statusInfo
    if (json.HasMember("statusInfo"))
    {
        ocpp::types::ocpp20::StatusInfoType20Converter statusInfo_converter;
        ret = ret && statusInfo_converter.fromJson(json["statusInfo"], data.statusInfo, error_code, error_message);
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a GetMonitoringReport20Conf to a JSON representation */
bool GetMonitoringReport20ConfConverter::toJson(const GetMonitoringReport20Conf& data, rapidjson::Document& json)
{
    bool ret = true;

    // customData
    if (data.customData.isSet())
    {
        ocpp::types::ocpp20::CustomDataType20Converter customData_converter;
        customData_converter.setAllocator(allocator);
        rapidjson::Document customData_doc;
        customData_doc.Parse("{}");
        ret = ret && customData_converter.toJson(data.customData, customData_doc);
        json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    // status
    fill(json, "status", ocpp::types::ocpp20::GenericDeviceModelStatusEnumType20Helper.toString(data.status));

    // statusInfo
    if (data.statusInfo.isSet())
    {
        ocpp::types::ocpp20::StatusInfoType20Converter statusInfo_converter;
        statusInfo_converter.setAllocator(allocator);
        rapidjson::Document statusInfo_doc;
        statusInfo_doc.Parse("{}");
        ret = ret && statusInfo_converter.toJson(data.statusInfo, statusInfo_doc);
        json.AddMember(rapidjson::StringRef("statusInfo"), statusInfo_doc.Move(), *allocator);
    }

    return ret;
}

} // namespace ocpp20
} // namespace messages
} // namespace ocpp