/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:InstallCertificateRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_INSTALLCERTIFICATE20_H
#define OPENOCPP_INSTALLCERTIFICATE20_H

#include "IMessageConverter.h"

#include "CustomDataType20.h"
#include "InstallCertificateStatusEnumType20.h"
#include "InstallCertificateUseEnumType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the InstallCertificate20 messages */
static const std::string INSTALLCERTIFICATE20_ACTION = "InstallCertificate";

/** @brief InstallCertificate20Req message */
struct InstallCertificate20Req
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType20> customData;
    /** @brief  */
    ocpp::types::ocpp20::InstallCertificateUseEnumType20 certificateType;
    /** @brief A PEM encoded X.509 certificate. */
    ocpp::types::CiStringType<5500u> certificate;
};

/** @brief InstallCertificate20Conf message */
struct InstallCertificate20Conf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType20> customData;
    /** @brief  */
    ocpp::types::ocpp20::InstallCertificateStatusEnumType20 status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType20> statusInfo;
};

// Message converters
MESSAGE_CONVERTERS(InstallCertificate20)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_INSTALLCERTIFICATE20_H