/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:NotifyEVChargingNeedsRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_NOTIFYEVCHARGINGNEEDS_H
#define OPENOCPP_OCPP20_NOTIFYEVCHARGINGNEEDS_H

#include "IMessageConverter.h"

#include "ChargingNeedsType20.h"
#include "CustomDataType20.h"
#include "NotifyEVChargingNeedsStatusEnumType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the NotifyEVChargingNeeds messages */
static const std::string NOTIFYEVCHARGINGNEEDS_ACTION = "NotifyEVChargingNeeds";

/** @brief NotifyEVChargingNeedsReq message */
struct NotifyEVChargingNeedsReq
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief Contains the maximum schedule tuples the car supports per schedule. */
    ocpp::types::Optional<int> maxScheduleTuples;
    /** @brief  */
    ocpp::types::ocpp20::ChargingNeedsType chargingNeeds;
    /** @brief Defines the EVSE and connector to which the EV is connected. EvseId may not be 0. */
    int evseId;
};

/** @brief NotifyEVChargingNeedsConf message */
struct NotifyEVChargingNeedsConf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType> customData;
    /** @brief  */
    ocpp::types::ocpp20::NotifyEVChargingNeedsStatusEnumType status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType> statusInfo;
};

// Message converters
MESSAGE_CONVERTERS(NotifyEVChargingNeeds)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_OCPP20_NOTIFYEVCHARGINGNEEDS_H