/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:ResetRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_RESET20_H
#define OPENOCPP_RESET20_H

#include "IMessageConverter.h"

#include "CustomDataType20.h"
#include "ResetEnumType20.h"
#include "ResetStatusEnumType20.h"
#include "StatusInfoType20.h"

namespace ocpp
{
namespace messages
{
namespace ocpp20
{

/** @brief Action corresponding to the Reset20 messages */
static const std::string RESET20_ACTION = "Reset";

/** @brief Reset20Req message */
struct Reset20Req
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType20> customData;
    /** @brief  */
    ocpp::types::ocpp20::ResetEnumType20 type;
    /** @brief This contains the ID of a specific EVSE that needs to be reset, instead of the entire Charging Station. */
    ocpp::types::Optional<int> evseId;
};

/** @brief Reset20Conf message */
struct Reset20Conf
{
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::CustomDataType20> customData;
    /** @brief  */
    ocpp::types::ocpp20::ResetStatusEnumType20 status;
    /** @brief  */
    ocpp::types::Optional<ocpp::types::ocpp20::StatusInfoType20> statusInfo;
};

// Message converters
MESSAGE_CONVERTERS(Reset20)

} // namespace ocpp20
} // namespace messages
} // namespace ocpp

#endif // OPENOCPP_RESET20_H