/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:SignCertificateRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_CERTIFICATESIGNINGUSEENUMTYPE_H
#define OPENOCPP_OCPP20_CERTIFICATESIGNINGUSEENUMTYPE_H

#include "EnumToStringFromString.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Indicates the type of certificate that is to be signed. When omitted the certificate is to be used for both the 15118 connection (if implemented) and the Charging Station to CSMS connection. */
enum class CertificateSigningUseEnumType
{
    ChargingStationCertificate,
    V2GCertificate,
};

/** @brief Helper to convert a CertificateSigningUseEnumType enum to string */
extern const EnumToStringFromString<CertificateSigningUseEnumType> CertificateSigningUseEnumTypeHelper;

} // namespace ocpp20
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP20_CERTIFICATESIGNINGUSEENUMTYPE_H