/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:RequestStartTransactionRequest
                                 OCPP 2.0.1 FINAL
*/

#include "ConsumptionCostType20.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Convert a ConsumptionCostType from a JSON representation */
bool ConsumptionCostTypeConverter::fromJson(const rapidjson::Value&       json,
                                            ConsumptionCostType&          data,
                                            std::string&                  error_code,
                                            [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // customData
    if (json.HasMember("customData"))
    {
        CustomDataTypeConverter customData_converter;
        ret = ret && customData_converter.fromJson(json["customData"], data.customData, error_code, error_message);
    }

    // startValue
    extract(json, "startValue", data.startValue);

    // cost
    if (json.HasMember("cost"))
    {
        const rapidjson::Value& cost_json = json["cost"];
        CostTypeConverter       cost_converter;
        for (auto it = cost_json.Begin(); ret && (it != cost_json.End()); ++it)
        {
            CostType& item = data.cost.emplace_back();
            ret            = ret && cost_converter.fromJson(*it, item, error_code, error_message);
        }
    }

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a ConsumptionCostType to a JSON representation */
bool ConsumptionCostTypeConverter::toJson(const ConsumptionCostType& data, rapidjson::Document& json)
{
    bool ret = true;

    // customData
    if (data.customData.isSet())
    {
        CustomDataTypeConverter customData_converter;
        customData_converter.setAllocator(allocator);
        rapidjson::Document customData_doc(rapidjson::kObjectType);
        ret = ret && customData_converter.toJson(data.customData, customData_doc);
        json.AddMember(rapidjson::StringRef("customData"), customData_doc.Move(), *allocator);
    }

    // startValue
    fill(json, "startValue", data.startValue);

    // cost

    rapidjson::Value  cost_json(rapidjson::kArrayType);
    CostTypeConverter cost_converter;
    cost_converter.setAllocator(allocator);
    for (const CostType& item : data.cost)
    {
        rapidjson::Document item_doc(rapidjson::kObjectType);
        ret = ret && cost_converter.toJson(item, item_doc);
        cost_json.PushBack(item_doc.Move(), *allocator);
    }
    json.AddMember(rapidjson::StringRef("cost"), cost_json.Move(), *allocator);

    return ret;
}

} // namespace ocpp20
} // namespace types
} // namespace ocpp