/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:RequestStartTransactionRequest
                                 OCPP 2.0.1 FINAL
*/

#include "CustomDataType20.h"

#include "IRpc.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Convert a CustomDataType from a JSON representation */
bool CustomDataTypeConverter::fromJson(const rapidjson::Value&       json,
                                       CustomDataType&               data,
                                       std::string&                  error_code,
                                       [[maybe_unused]] std::string& error_message)
{
    bool ret = true;

    // vendorId
    extract(json, "vendorId", data.vendorId);

    if (!ret)
    {
        error_code = ocpp::rpc::IRpc::RPC_ERROR_TYPE_CONSTRAINT_VIOLATION;
    }

    return ret;
}

/** @brief Convert a CustomDataType to a JSON representation */
bool CustomDataTypeConverter::toJson(const CustomDataType& data, rapidjson::Document& json)
{
    bool ret = true;

    // vendorId
    fill(json, "vendorId", data.vendorId);

    return ret;
}

} // namespace ocpp20
} // namespace types
} // namespace ocpp