/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:GetInstalledCertificateIdsRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_GETINSTALLEDCERTIFICATESTATUSENUMTYPE20_H
#define OPENOCPP_GETINSTALLEDCERTIFICATESTATUSENUMTYPE20_H

#include "EnumToStringFromString.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Charging Station indicates if it can process the request. */
enum class GetInstalledCertificateStatusEnumType20
{
    Accepted,
    NotFound,
};

/** @brief Helper to convert a GetInstalledCertificateStatusEnumType20 enum to string */
extern const EnumToStringFromString<GetInstalledCertificateStatusEnumType20> GetInstalledCertificateStatusEnumType20Helper;

} // namespace ocpp20
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_GETINSTALLEDCERTIFICATESTATUSENUMTYPE20_H