/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:RequestStartTransactionRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_IDTOKENTYPE_H
#define OPENOCPP_OCPP20_IDTOKENTYPE_H

#include "AdditionalInfoType20.h"
#include "CustomDataType20.h"
#include "IdTokenEnumType20.h"

#include "CiStringType.h"
#include "IMessageConverter.h"
#include "Optional.h"
#include <vector>

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Contains a case insensitive identifier to use for the authorization and the type of authorization to support multiple forms of identifiers.
 */
struct IdTokenType
{
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
    /** @brief  */
    std::vector<AdditionalInfoType> additionalInfo;
    /** @brief IdToken is case insensitive. Might hold the hidden id of an RFID tag, but can for example also contain a UUID. */
    ocpp::types::CiStringType<36u> idToken;
    /** @brief  */
    IdTokenEnumType type;
};

/** @brief Converter class for IdTokenType type */
class IdTokenTypeConverter : public ocpp::messages::IMessageConverter<IdTokenType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<IdTokenType>* clone() const override { return new IdTokenTypeConverter(); }

    /** @brief Convert a IdTokenType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  IdTokenType&                  data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a IdTokenType to a JSON representation */
    bool toJson(const IdTokenType& data, rapidjson::Document& json) override;
};

} // namespace ocpp20
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP20_IDTOKENTYPE_H