/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:TransactionEventRequest
                                 OCPP 2.0.1 FINAL
*/

#include "ReasonEnumType20.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief Helper to convert a ReasonEnumType enum to string */
const EnumToStringFromString<ReasonEnumType> ReasonEnumTypeHelper = {
    {ReasonEnumType::DeAuthorized, "DeAuthorized"},
    {ReasonEnumType::EmergencyStop, "EmergencyStop"},
    {ReasonEnumType::EnergyLimitReached, "EnergyLimitReached"},
    {ReasonEnumType::EVDisconnected, "EVDisconnected"},
    {ReasonEnumType::GroundFault, "GroundFault"},
    {ReasonEnumType::ImmediateReset, "ImmediateReset"},
    {ReasonEnumType::Local, "Local"},
    {ReasonEnumType::LocalOutOfCredit, "LocalOutOfCredit"},
    {ReasonEnumType::MasterPass, "MasterPass"},
    {ReasonEnumType::Other, "Other"},
    {ReasonEnumType::OvercurrentFault, "OvercurrentFault"},
    {ReasonEnumType::PowerLoss, "PowerLoss"},
    {ReasonEnumType::PowerQuality, "PowerQuality"},
    {ReasonEnumType::Reboot, "Reboot"},
    {ReasonEnumType::Remote, "Remote"},
    {ReasonEnumType::SOCLimitReached, "SOCLimitReached"},
    {ReasonEnumType::StoppedByEV, "StoppedByEV"},
    {ReasonEnumType::TimeLimitReached, "TimeLimitReached"},
    {ReasonEnumType::Timeout, "Timeout"},
};

} // namespace ocpp20
} // namespace types
} // namespace ocpp