/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/*
    Generated by json2cpp from : urn:OCPP:Cp:2:2020:3:SetVariablesRequest
                                 OCPP 2.0.1 FINAL
*/

#ifndef OPENOCPP_OCPP20_SETVARIABLERESULTTYPE_H
#define OPENOCPP_OCPP20_SETVARIABLERESULTTYPE_H

#include "AttributeEnumType20.h"
#include "ComponentType20.h"
#include "CustomDataType20.h"
#include "SetVariableStatusEnumType20.h"
#include "StatusInfoType20.h"
#include "VariableType20.h"

#include "IMessageConverter.h"
#include "Optional.h"

namespace ocpp
{
namespace types
{
namespace ocpp20
{

/** @brief  */
struct SetVariableResultType
{
    /** @brief  */
    ocpp::types::Optional<CustomDataType> customData;
    /** @brief  */
    ocpp::types::Optional<AttributeEnumType> attributeType;
    /** @brief  */
    SetVariableStatusEnumType attributeStatus;
    /** @brief  */
    ocpp::types::Optional<StatusInfoType> attributeStatusInfo;
    /** @brief  */
    ComponentType component;
    /** @brief  */
    VariableType variable;
};

/** @brief Converter class for SetVariableResultType type */
class SetVariableResultTypeConverter : public ocpp::messages::IMessageConverter<SetVariableResultType>
{
  public:
    /** @brief Clone the converter */
    ocpp::messages::IMessageConverter<SetVariableResultType>* clone() const override { return new SetVariableResultTypeConverter(); }

    /** @brief Convert a SetVariableResultType from a JSON representation */
    bool fromJson(const rapidjson::Value&       json,
                  SetVariableResultType&        data,
                  std::string&                  error_code,
                  [[maybe_unused]] std::string& error_message) override;

    /** @brief Convert a SetVariableResultType to a JSON representation */
    bool toJson(const SetVariableResultType& data, rapidjson::Document& json) override;
};

} // namespace ocpp20
} // namespace types
} // namespace ocpp

#endif // OPENOCPP_OCPP20_SETVARIABLERESULTTYPE_H