/*
Copyright (c) 2020 Cedric Jimenez
This file is part of OpenOCPP.

OpenOCPP is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 2.1 of the License, or
(at your option) any later version.

OpenOCPP is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with OpenOCPP. If not, see <http://www.gnu.org/licenses/>.
*/

/* Generated by json2cpp */

#ifndef OPENOCPP_OCPP20_CENTRALSYSTEMHANDLER20_H
#define OPENOCPP_OCPP20_CENTRALSYSTEMHANDLER20_H

#include "CancelReservation20.h"
#include "CertificateSigned20.h"
#include "ChangeAvailability20.h"
#include "ClearCache20.h"
#include "ClearChargingProfile20.h"
#include "ClearDisplayMessage20.h"
#include "ClearVariableMonitoring20.h"
#include "CustomerInformation20.h"
#include "DataTransfer20.h"
#include "DeleteCertificate20.h"
#include "GenericMessageHandler.h"
#include "Get15118EVCertificate20.h"
#include "GetBaseReport20.h"
#include "GetCertificateStatus20.h"
#include "GetChargingProfiles20.h"
#include "GetCompositeSchedule20.h"
#include "GetDisplayMessages20.h"
#include "GetInstalledCertificateIds20.h"
#include "GetLocalListVersion20.h"
#include "GetLog20.h"
#include "GetMonitoringReport20.h"
#include "GetReport20.h"
#include "GetTransactionStatus20.h"
#include "GetVariables20.h"
#include "IChargePointProxy20.h"
#include "IRpc.h"
#include "InstallCertificate20.h"
#include "Logger.h"
#include "PublishFirmware20.h"
#include "RequestStartTransaction20.h"
#include "RequestStopTransaction20.h"
#include "ReserveNow20.h"
#include "Reset20.h"
#include "SendLocalList20.h"
#include "SetChargingProfile20.h"
#include "SetDisplayMessage20.h"
#include "SetMonitoringBase20.h"
#include "SetMonitoringLevel20.h"
#include "SetNetworkProfile20.h"
#include "SetVariableMonitoring20.h"
#include "SetVariables20.h"
#include "TriggerMessage20.h"
#include "UnlockConnector20.h"
#include "UnpublishFirmware20.h"
#include "UpdateFirmware20.h"

namespace ocpp
{
namespace config
{
class ILocalControllerConfig20;
} // namespace config
namespace messages
{
class MessageDispatcher;
namespace ocpp20
{
class MessagesConverter20;
} // namespace ocpp20
} // namespace messages

namespace localcontroller
{
namespace ocpp20
{

/** @brief Handler for central system requests */
class CentralSystemHandler20
    : public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::CancelReservationReq,
                                                   ocpp::messages::ocpp20::CancelReservationConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::CertificateSignedReq,
                                                   ocpp::messages::ocpp20::CertificateSignedConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ChangeAvailabilityReq,
                                                   ocpp::messages::ocpp20::ChangeAvailabilityConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ClearCacheReq, ocpp::messages::ocpp20::ClearCacheConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ClearChargingProfileReq,
                                                   ocpp::messages::ocpp20::ClearChargingProfileConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ClearDisplayMessageReq,
                                                   ocpp::messages::ocpp20::ClearDisplayMessageConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ClearVariableMonitoringReq,
                                                   ocpp::messages::ocpp20::ClearVariableMonitoringConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::CustomerInformationReq,
                                                   ocpp::messages::ocpp20::CustomerInformationConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::DataTransferReq, ocpp::messages::ocpp20::DataTransferConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::DeleteCertificateReq,
                                                   ocpp::messages::ocpp20::DeleteCertificateConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::Get15118EVCertificateReq,
                                                   ocpp::messages::ocpp20::Get15118EVCertificateConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetBaseReportReq, ocpp::messages::ocpp20::GetBaseReportConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetCertificateStatusReq,
                                                   ocpp::messages::ocpp20::GetCertificateStatusConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetChargingProfilesReq,
                                                   ocpp::messages::ocpp20::GetChargingProfilesConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetCompositeScheduleReq,
                                                   ocpp::messages::ocpp20::GetCompositeScheduleConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetDisplayMessagesReq,
                                                   ocpp::messages::ocpp20::GetDisplayMessagesConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetInstalledCertificateIdsReq,
                                                   ocpp::messages::ocpp20::GetInstalledCertificateIdsConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetLocalListVersionReq,
                                                   ocpp::messages::ocpp20::GetLocalListVersionConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetLogReq, ocpp::messages::ocpp20::GetLogConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetMonitoringReportReq,
                                                   ocpp::messages::ocpp20::GetMonitoringReportConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetReportReq, ocpp::messages::ocpp20::GetReportConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetTransactionStatusReq,
                                                   ocpp::messages::ocpp20::GetTransactionStatusConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::GetVariablesReq, ocpp::messages::ocpp20::GetVariablesConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::InstallCertificateReq,
                                                   ocpp::messages::ocpp20::InstallCertificateConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::PublishFirmwareReq, ocpp::messages::ocpp20::PublishFirmwareConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::RequestStartTransactionReq,
                                                   ocpp::messages::ocpp20::RequestStartTransactionConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::RequestStopTransactionReq,
                                                   ocpp::messages::ocpp20::RequestStopTransactionConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ReserveNowReq, ocpp::messages::ocpp20::ReserveNowConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::ResetReq, ocpp::messages::ocpp20::ResetConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SendLocalListReq, ocpp::messages::ocpp20::SendLocalListConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetChargingProfileReq,
                                                   ocpp::messages::ocpp20::SetChargingProfileConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetDisplayMessageReq,
                                                   ocpp::messages::ocpp20::SetDisplayMessageConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetMonitoringBaseReq,
                                                   ocpp::messages::ocpp20::SetMonitoringBaseConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetMonitoringLevelReq,
                                                   ocpp::messages::ocpp20::SetMonitoringLevelConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetNetworkProfileReq,
                                                   ocpp::messages::ocpp20::SetNetworkProfileConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetVariableMonitoringReq,
                                                   ocpp::messages::ocpp20::SetVariableMonitoringConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::SetVariablesReq, ocpp::messages::ocpp20::SetVariablesConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::TriggerMessageReq, ocpp::messages::ocpp20::TriggerMessageConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::UnlockConnectorReq, ocpp::messages::ocpp20::UnlockConnectorConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::UnpublishFirmwareReq,
                                                   ocpp::messages::ocpp20::UnpublishFirmwareConf>,
      public ocpp::messages::GenericMessageHandler<ocpp::messages::ocpp20::UpdateFirmwareReq, ocpp::messages::ocpp20::UpdateFirmwareConf>
{
  public:
    /**
     * @brief Constructor
     * @param identifier Charge point's identifier
     * @param messages_converter Converter from/to OCPP to/from JSON messages
     * @param msg_dispatcher Message dispatcher
     * @param stack_config Stack configuration
     */
    CentralSystemHandler20(const std::string&                                 identifier,
                           const ocpp::messages::ocpp20::MessagesConverter20& messages_converter,
                           ocpp::messages::MessageDispatcher&                 msg_dispatcher);

    /** @brief Destructor */
    virtual ~CentralSystemHandler20();

    /**
     * @brief Set the proxy to forward requests to the charge point
     * @param central_system Proxy to forward requests to the charge point
     */
    void setChargePointProxy(std::weak_ptr<IChargePointProxy20> charge_point) { m_charge_point = charge_point; }

    // OCPP handlers
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::CancelReservationReq& request,
                       ocpp::messages::ocpp20::CancelReservationConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::CertificateSignedReq& request,
                       ocpp::messages::ocpp20::CertificateSignedConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ChangeAvailabilityReq& request,
                       ocpp::messages::ocpp20::ChangeAvailabilityConf&      response,
                       std::string&                                         error_code,
                       std::string&                                         error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ClearCacheReq& request,
                       ocpp::messages::ocpp20::ClearCacheConf&      response,
                       std::string&                                 error_code,
                       std::string&                                 error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ClearChargingProfileReq& request,
                       ocpp::messages::ocpp20::ClearChargingProfileConf&      response,
                       std::string&                                           error_code,
                       std::string&                                           error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ClearDisplayMessageReq& request,
                       ocpp::messages::ocpp20::ClearDisplayMessageConf&      response,
                       std::string&                                          error_code,
                       std::string&                                          error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ClearVariableMonitoringReq& request,
                       ocpp::messages::ocpp20::ClearVariableMonitoringConf&      response,
                       std::string&                                              error_code,
                       std::string&                                              error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::CustomerInformationReq& request,
                       ocpp::messages::ocpp20::CustomerInformationConf&      response,
                       std::string&                                          error_code,
                       std::string&                                          error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::DataTransferReq& request,
                       ocpp::messages::ocpp20::DataTransferConf&      response,
                       std::string&                                   error_code,
                       std::string&                                   error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::DeleteCertificateReq& request,
                       ocpp::messages::ocpp20::DeleteCertificateConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::Get15118EVCertificateReq& request,
                       ocpp::messages::ocpp20::Get15118EVCertificateConf&      response,
                       std::string&                                            error_code,
                       std::string&                                            error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetBaseReportReq& request,
                       ocpp::messages::ocpp20::GetBaseReportConf&      response,
                       std::string&                                    error_code,
                       std::string&                                    error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetCertificateStatusReq& request,
                       ocpp::messages::ocpp20::GetCertificateStatusConf&      response,
                       std::string&                                           error_code,
                       std::string&                                           error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetChargingProfilesReq& request,
                       ocpp::messages::ocpp20::GetChargingProfilesConf&      response,
                       std::string&                                          error_code,
                       std::string&                                          error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetCompositeScheduleReq& request,
                       ocpp::messages::ocpp20::GetCompositeScheduleConf&      response,
                       std::string&                                           error_code,
                       std::string&                                           error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetDisplayMessagesReq& request,
                       ocpp::messages::ocpp20::GetDisplayMessagesConf&      response,
                       std::string&                                         error_code,
                       std::string&                                         error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetInstalledCertificateIdsReq& request,
                       ocpp::messages::ocpp20::GetInstalledCertificateIdsConf&      response,
                       std::string&                                                 error_code,
                       std::string&                                                 error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetLocalListVersionReq& request,
                       ocpp::messages::ocpp20::GetLocalListVersionConf&      response,
                       std::string&                                          error_code,
                       std::string&                                          error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetLogReq& request,
                       ocpp::messages::ocpp20::GetLogConf&      response,
                       std::string&                             error_code,
                       std::string&                             error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetMonitoringReportReq& request,
                       ocpp::messages::ocpp20::GetMonitoringReportConf&      response,
                       std::string&                                          error_code,
                       std::string&                                          error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetReportReq& request,
                       ocpp::messages::ocpp20::GetReportConf&      response,
                       std::string&                                error_code,
                       std::string&                                error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetTransactionStatusReq& request,
                       ocpp::messages::ocpp20::GetTransactionStatusConf&      response,
                       std::string&                                           error_code,
                       std::string&                                           error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::GetVariablesReq& request,
                       ocpp::messages::ocpp20::GetVariablesConf&      response,
                       std::string&                                   error_code,
                       std::string&                                   error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::InstallCertificateReq& request,
                       ocpp::messages::ocpp20::InstallCertificateConf&      response,
                       std::string&                                         error_code,
                       std::string&                                         error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::PublishFirmwareReq& request,
                       ocpp::messages::ocpp20::PublishFirmwareConf&      response,
                       std::string&                                      error_code,
                       std::string&                                      error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::RequestStartTransactionReq& request,
                       ocpp::messages::ocpp20::RequestStartTransactionConf&      response,
                       std::string&                                              error_code,
                       std::string&                                              error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::RequestStopTransactionReq& request,
                       ocpp::messages::ocpp20::RequestStopTransactionConf&      response,
                       std::string&                                             error_code,
                       std::string&                                             error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ReserveNowReq& request,
                       ocpp::messages::ocpp20::ReserveNowConf&      response,
                       std::string&                                 error_code,
                       std::string&                                 error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::ResetReq& request,
                       ocpp::messages::ocpp20::ResetConf&      response,
                       std::string&                            error_code,
                       std::string&                            error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SendLocalListReq& request,
                       ocpp::messages::ocpp20::SendLocalListConf&      response,
                       std::string&                                    error_code,
                       std::string&                                    error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetChargingProfileReq& request,
                       ocpp::messages::ocpp20::SetChargingProfileConf&      response,
                       std::string&                                         error_code,
                       std::string&                                         error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetDisplayMessageReq& request,
                       ocpp::messages::ocpp20::SetDisplayMessageConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetMonitoringBaseReq& request,
                       ocpp::messages::ocpp20::SetMonitoringBaseConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetMonitoringLevelReq& request,
                       ocpp::messages::ocpp20::SetMonitoringLevelConf&      response,
                       std::string&                                         error_code,
                       std::string&                                         error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetNetworkProfileReq& request,
                       ocpp::messages::ocpp20::SetNetworkProfileConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetVariableMonitoringReq& request,
                       ocpp::messages::ocpp20::SetVariableMonitoringConf&      response,
                       std::string&                                            error_code,
                       std::string&                                            error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::SetVariablesReq& request,
                       ocpp::messages::ocpp20::SetVariablesConf&      response,
                       std::string&                                   error_code,
                       std::string&                                   error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::TriggerMessageReq& request,
                       ocpp::messages::ocpp20::TriggerMessageConf&      response,
                       std::string&                                     error_code,
                       std::string&                                     error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::UnlockConnectorReq& request,
                       ocpp::messages::ocpp20::UnlockConnectorConf&      response,
                       std::string&                                      error_code,
                       std::string&                                      error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::UnpublishFirmwareReq& request,
                       ocpp::messages::ocpp20::UnpublishFirmwareConf&      response,
                       std::string&                                        error_code,
                       std::string&                                        error_message) override;
    /** @copydoc bool GenericMessageHandler<RequestType, ResponseType>::handleMessage(const RequestType& request,
     *                                                                                ResponseType& response,
     *                                                                                std::string& error_code,
     *                                                                                std::string& error_message)
     */
    bool handleMessage(const ocpp::messages::ocpp20::UpdateFirmwareReq& request,
                       ocpp::messages::ocpp20::UpdateFirmwareConf&      response,
                       std::string&                                     error_code,
                       std::string&                                     error_message) override;

  private:
    /** @brief Charge point's identifier */
    const std::string m_identifier;
    /** @brief Proxy to forward requests to the charge point */
    std::weak_ptr<IChargePointProxy20> m_charge_point;

    /**
     * @brief Forward a call request to the Charge Point
     * @param action RPC action for the request
     * @param request Request payload
     * @param response Response payload
     * @param error Error code to return to the Charge Point, empty if no error
     * @param message Error message to return to the Charge Point, empty if no error
     * @return true if the request has been sent and a response has been received, false otherwise
     */
    template <typename RequestType, typename ResponseType>
    bool forward(const std::string& action, const RequestType& request, ResponseType& response, std::string& error, std::string& message)
    {
        bool ret = false;

        // Get charge point proxy
        auto charge_point = m_charge_point.lock();
        if (charge_point)
        {
            // Try to forward message
            std::string cs_error;
            std::string cs_message;
            ret = charge_point->call(request, response, cs_error, cs_message);
            if (!ret)
            {
                // Check timeout or error response
                if (cs_error.empty())
                {
                    LOG_WARNING << "[" << m_identifier << "] - Unable to forward [" << action << "] request";
                }
                else
                {
                    LOG_WARNING << "[" << m_identifier << "] - CallError [" << cs_error << "] received on [" << action << "] request";
                    error   = cs_error.c_str();
                    message = cs_message;
                }
            }
        }
        else
        {
            LOG_WARNING << "[" << m_identifier << "] - Unable to forward [" << action << "] request";
        }

        return ret;
    }
};

} // namespace ocpp20
} // namespace localcontroller
} // namespace ocpp

#endif // OPENOCPP_OCPP20_CENTRALSYSTEMHANDLER20_H