name: Unit test in Debug build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make gcc Debug
      run: make gcc BUILD_TYPE=Debug
    - name: unit tests gcc Debug
      run: make tests-gcc BUILD_TYPE=Debug
    - name: make clang Debug
      run: make clang BUILD_TYPE=Debug
    - name: unit tests clang
      run: make tests-clang BUILD_TYPE=Debug
