name: Unit test in Release build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: make gcc Release
      run: make gcc BUILD_TYPE=Release
    - name: unit tests gcc Release
      run: make tests-gcc BUILD_TYPE=Release
    - name: make clang Release
      run: make clang BUILD_TYPE=Release
    - name: unit tests clang
      run: make tests-clang BUILD_TYPE=Release
